version: '3'

tasks:
  build:
    cmds:
      - go build -o bin/api
    silent: true

  run: 
    cmds:
      - ./bin/api
    silent: true
    deps: [build]

  seed: 
    cmds:
      - go run scripts/seed.go
    silent: true
    deps: [build]

  test:
    cmds:
      - go test -v ./...
    silent: true